# Generated by Django 4.1.6 on 2023-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_alter_ads_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(),
        ),
    ]
