# Generated by Django 4.1.6 on 2023-02-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='location_id',
            new_name='location',
        ),
    ]
