# Generated by Django 4.1.6 on 2023-02-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
